version: "3.9"
services:
  # BASE DE DATOS
  postgres:
    image: postgres
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - app_network
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: "prueba@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "80:80"
    networks:
      - app_network
    depends_on:
      - postgres

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - APP_ENV=production
      - LOG_LEVEL=info
    volumes:
      - ./docs:/app/docs
    networks:
      - app_network
    depends_on:
      - postgres

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
